// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCN4B-5mOMjKEca0TXJSzR4C8f3A4s4PE',
    appId: '1:104720500358:web:bc8b066bc700a8ece97307',
    messagingSenderId: '104720500358',
    projectId: 'flutter-chat-app-242d8',
    authDomain: 'flutter-chat-app-242d8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-242d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6dHo7CVEq8fHO7oxi4C75e_Yp0LKkKxM',
    appId: '1:104720500358:android:5b63dcc98358f47ce97307',
    messagingSenderId: '104720500358',
    projectId: 'flutter-chat-app-242d8',
    storageBucket: 'flutter-chat-app-242d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAny2ON6xcDQV1yeabPZlwRRaHDITsH5to',
    appId: '1:104720500358:ios:658624f6e1279ff5e97307',
    messagingSenderId: '104720500358',
    projectId: 'flutter-chat-app-242d8',
    storageBucket: 'flutter-chat-app-242d8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
